import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryProviders } from "@/components/providers/QueryProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <QueryProviders>
          <Toaster position="bottom-right" />
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
